# -*- coding: utf-8 -*-
"""210820numpy 배열 복습.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fE_k4bLDrAoI44wt4CBKZD5cJFuZ5Vcj
"""

import numpy as np

arr = np.arange(24).reshape(3,2,4) #(axis0[ , axis1[[]] , axis2 원소의 갯수)
arr

arr[:,:,0:2]

arr[0:2, 1, 2:]

tensor = np.arange(120).reshape(2,3,4,5)
tensor

tensor[0,1,2:,3:]

tensor[1,1,1:3,1:3] #86,87 ,91,92추출

