# -*- coding: utf-8 -*-
"""210818 pandas module을 통한 data확인.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13chqfpgR84Zz56hhWxs50Nkm0gde8hwG
"""

import pandas as pd
import folium

state_unemplyment='/content/drive/MyDrive/Colab Notebooks/02. folium_US_Unemployment_Oct2012.csv'

state_data = pd.read_csv(state_unemplyment)
state_data.head()

state_geo='/content/drive/MyDrive/Colab Notebooks/02. folium_us-states.json'

map=folium.Map(location=[40,-98],zoom_start=4)
folium.Choropleth(geo_data=state_geo, data = state_data , columns= ['State' , 'Unemployment'],
               key_on = 'feature.id' , 
               fill_color='YlGn' ,
               legend_name = 'Unemployment Rate(%)').add_to(map)
folium.LayerControl().add_to(map)
map

